version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_USER=ankurgajurel
      - DB_PASS=password
      - DB_NAME=a5ittask
      - DB_HOST=db
      - DB_PORT=5432
      - DB_TYPE=postgres

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: a5ittask
      POSTGRES_USER: ankurgajurel
      POSTGRES_PASSWORD: password
